name: ATMsigns
main: me.ellbristow.ATMsigns.ATMsigns
version: 1.3.4
author: ellbristow
dev-url: http://dev.bukkit.org/server-mods/atmsigns
description: >
             Deposit/Withdraw items for currency using signs.
depend: [Vault]
permissions:
  atmsigns.*:
    description: All permissions.
    children:
      atmsigns.create: true
      atmsigns.break: true
      atmsigns.use: true
  atmsigns.create:
    description: Can create deposit and withdraw signs.
  atmsigns.break:
    description: Can destroy ATM signs.
  atmsigns.use:
    description: Can use ATM signs.
